### ISSUE TITLE
Wrong import of pickr

### ISSUE THREAD

**Issue by sebastian-marinescu** [yharaskrik/ngx-pickr#2]
When building for production with `ng build --prod` I get an error:

```
ERROR in ./node_modules/ngx-pickr/fesm5/ngx-pickr.js
Module not found: Error: Can't resolve 'node_modules/@simonwep/pickr/dist/pickr.min' in '/home/name/otherfolder/node_modules/ngx-pickr/fesm5'
``` 

This is because you import pickr with a leading 'node_modules': 
https://github.com/yharaskrik/ngx-pickr/blob/master/projects/ngx-pickr/src/lib/ngx-pickr.directive.ts#L14

`import Pickr from '@simonwep/pickr/dist/pickr.min';` should be sufficient. 
And add it as peer-dependency.

**Comment by yharaskrik** [comment]
Sorry for the late response @sebastian-marinescu , this is fixed in v0.1.0 on npm now!
